#!/usr/bin/env python3
"""3D models for the two parts KiCad has none for.

  * J1 USB-C: the vendor model from LCSC/EasyEDA (C165948), downloaded with
        uvx easyeda2kicad --lcsc_id=C165948 --3d --output <dir>/ee
    and attached to a project copy of KiCad's stock HRO footprint.
  * J2 M.2 socket: LCSC/EasyEDA has no model for MLD-NGFF-E-4.2H (C52766479),
    so the housing is built here from the dimensions on the MLD drawing, and a
    second, translucent model shows the 2230 card with its component zones.
    Both are envelopes (maximum material), which is what a clearance check
    wants; neither is a cosmetic model.

All numbers are footprint-local mm (origin midway between the pad rows, +Y is
the card side, where the locating pegs and even pins are).

    "C:\\Program Files\\KiCad\\10.0\\bin\\python.exe" build_models.py
"""
import os
import re
import shutil

HERE = os.path.dirname(os.path.abspath(__file__))
SHAPES = os.path.join(HERE, "library", "HaLowAdapter.3dshapes")
PRETTY = os.path.join(HERE, "library", "HaLowAdapter.pretty")
STOCK = r"C:\Program Files\KiCad\10.0\share\kicad\footprints"

# ---- MLD-NGFF-E-4.2H, from the drawing -------------------------------------
PEG_Y = 1.50                    # locating pegs, footprint-local
CARD_STOP_Y = PEG_Y - 1.75      # section O-O: slot back wall is 1.75 behind the pegs
HOUSING_X = 21.85 / 2 + 0.075   # 21.85 +/- 0.15 wide
HOUSING_REAR_Y = PEG_Y - 5.00   # 5.60 to the rear tail tip, tail 0.60
HOUSING_FRONT_Y = PEG_Y + 2.55 - 0.65   # 2.55 to the front tail tip, tail 0.65
MOUTH_Y = CARD_STOP_Y + 1.93    # upper lip ends 1.93 in front of the back wall
HOUSING_H = 4.20                # 4.05 +/- 0.15
SLOT_Z0 = 2.47                  # top of the lower front block
CARD_Z0 = 2.92 - 0.40           # card centre 2.92 up, card 0.80 thick
CARD_T = 0.80
CARD_W, CARD_L = 22.0, 30.0
TOP_ZONE_FROM, TOP_ZONE_H = 4.00, 1.50      # module drawing: component zone limits
BOT_ZONE_FROM, BOT_ZONE_H = 5.20, 1.35
UNDER_CARD_MAX = 0.90           # "0.90 Max component ht. allowable" on the main board


def box(x0, y0, z0, x1, y1, z1, rgb, alpha=0.0):
    """One VRML box from footprint-local mm (Y down) to KiCad's model frame
    (Y up, units of 0.1 inch)."""
    k = 1 / 2.54
    ys = sorted((-y0, -y1))
    xs, zs = sorted((x0, x1)), sorted((z0, z1))
    p = [(x * k, y * k, z * k) for z in zs for y in ys for x in xs]
    pts = ", ".join("%.5f %.5f %.5f" % q for q in p)
    faces = "0,2,3,1,-1, 4,5,7,6,-1, 0,1,5,4,-1, 2,6,7,3,-1, 0,4,6,2,-1, 1,3,7,5,-1"
    return ("Shape { appearance Appearance { material Material { diffuseColor %g %g %g "
            "ambientIntensity 0.3 specularColor 0.2 0.2 0.2 shininess 0.3 transparency %g } }\n"
            "  geometry IndexedFaceSet { solid FALSE coord Coordinate { point [ %s ] }\n"
            "  coordIndex [ %s ] } }\n" % (rgb + (alpha, pts, faces)))


def write_wrl(name, shapes):
    path = os.path.join(SHAPES, name)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("#VRML V2.0 utf8\n# generated by build_models.py from the MLD-NGFF-E-4.2H drawing\n")
        f.write("".join(shapes))
    print("wrote", os.path.relpath(path, HERE))


def socket_models():
    dark = (0.12, 0.12, 0.13)
    hx = HOUSING_X
    write_wrl("MLD-NGFF-E-4.2H_envelope.wrl", [
        box(-hx, HOUSING_REAR_Y, 0, hx, HOUSING_FRONT_Y, SLOT_Z0, dark),          # lower block
        box(-hx, HOUSING_REAR_Y, SLOT_Z0, hx, CARD_STOP_Y, HOUSING_H, dark),       # rear wall
        box(-hx, CARD_STOP_Y, SLOT_Z0 + 0.95, hx, MOUTH_Y, HOUSING_H, dark),       # upper lip
    ])
    y0, y1 = CARD_STOP_Y, CARD_STOP_Y + CARD_L
    w = CARD_W / 2
    write_wrl("M2_2230_card_envelope.wrl", [
        box(-w, y0, CARD_Z0, w, y1, CARD_Z0 + CARD_T, (0.05, 0.45, 0.15), 0.35),
        box(-w, y0 + TOP_ZONE_FROM, CARD_Z0 + CARD_T, w, y1 - 3.5,
            CARD_Z0 + CARD_T + TOP_ZONE_H, (0.9, 0.8, 0.2), 0.75),
        box(-w, y0 + BOT_ZONE_FROM, CARD_Z0 - BOT_ZONE_H, w, y1 - 3.5, CARD_Z0,
            (0.95, 0.5, 0.1), 0.75),
    ])
    fp = os.path.join(PRETTY, "CONN-SMD_MLD-NGFF-E-4.2H.kicad_mod")
    t = open(fp, encoding="utf-8").read()
    t = re.sub(r"\s*\(model [^\n]*\n(?:\s+\((?:offset|scale|rotate)[^\n]*\n)+\s*\)", "", t)
    models = "".join(
        '\t(model "${KIPRJMOD}/library/HaLowAdapter.3dshapes/%s"\n'
        "\t\t(offset (xyz 0 0 0))\n\t\t(scale (xyz 1 1 1))\n\t\t(rotate (xyz 0 0 0))\n\t)\n" % n
        for n in ("MLD-NGFF-E-4.2H_envelope.wrl", "M2_2230_card_envelope.wrl"))
    t = t.rstrip()
    assert t.endswith(")")
    t = t[:-1].rstrip() + "\n" + models + ")\n"
    open(fp, "w", encoding="utf-8", newline="\n").write(t)
    print("attached 2 models to", os.path.basename(fp))


def usb_c(download_dir):
    name = "USB-C_SMD-TYPE-C-31-M-12_1"
    for ext in (".wrl", ".step"):
        src = os.path.join(download_dir, name + ext)
        if os.path.exists(src):
            shutil.copy2(src, os.path.join(SHAPES, name + ext))
    stock = os.path.join(STOCK, "Connector_USB.pretty", "USB_C_Receptacle_HRO_TYPE-C-31-M-12.kicad_mod")
    t = open(stock, encoding="utf-8").read()
    # The EasyEDA model's origin is its own footprint's: shell stakes at
    # y = -1.71 / +2.47 there, -3.13 / +1.05 in KiCad's footprint -> 1.42 mm.
    new = ('(model "${KIPRJMOD}/library/HaLowAdapter.3dshapes/%s.wrl"\n'
           "\t\t(offset\n\t\t\t(xyz 0 1.42 0)\n\t\t)\n\t\t(scale\n\t\t\t(xyz 1 1 1)\n\t\t)\n"
           "\t\t(rotate\n\t\t\t(xyz 0 0 180)\n\t\t)\n\t)" % name)
    i = t.index("(model ")
    depth, j = 0, i
    while True:
        depth += {"(": 1, ")": -1}.get(t[j], 0)
        j += 1
        if depth == 0:
            break
    t = t[:i] + new + t[j:]
    out = os.path.join(PRETTY, "USB_C_Receptacle_HRO_TYPE-C-31-M-12.kicad_mod")
    open(out, "w", encoding="utf-8", newline="\n").write(t)
    print("wrote", os.path.relpath(out, HERE))


if __name__ == "__main__":
    import sys
    socket_models()
    if len(sys.argv) > 1:
        usb_c(sys.argv[1])
