M48
; DRILL file KiCad 10.0.6 date 2026-09-20T14:32:54
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-20T14:32:54-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.600
%
G90
G05
T1
X5.75Y-18.61
X5.75Y-24.39
T2
X23.5Y-31.5
T3
X23.5Y-11.5
M30
